### ISSUE TITLE
xcode crashes everytime you begin typing in the help field

### ISSUE THREAD

**Issue by ampm** [alexkrzyzanowski/xcode-gitflow-plugin#11]
Process:               Xcode [65968]
Path:                  /Applications/Xcode.app/Contents/MacOS/Xcode
Identifier:            com.apple.dt.Xcode
Version:               7.3 (10183.3)
Build Info:            IDEFrameworks-10183003000000000~2
App Item ID:           497799835
App External ID:       816750016
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Xcode [65968]

Application Specific Information:
ProductBuildVersion: 7D175
UNCAUGHT EXCEPTION (NSInvalidArgumentException): **\* -[NSURL initWithString:relativeToURL:]: nil string parameter
UserInfo: (null)
Hints: None
Backtrace:
  0   **exceptionPreprocess (in CoreFoundation)
  1   DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2   objc_exception_throw (in libobjc.A.dylib)
  3   +[NSException raise:format:](in CoreFoundation)
  4   -[NSURL(NSURL) initWithString:relativeToURL:](in Foundation)
  5   -[GitflowCore projectDirectoryPath] at /Users/xx/Library/Application Support/Alcatraz/Plug-ins/gitflow/gitflow/GitflowCore.m:85 (in gitflow)
  6   -[GitflowCore listEntity:] at /Users/xx/Library/Application Support/Alcatraz/Plug-ins/gitflow/gitflow/GitflowCore.m:39 (in gitflow)
  7   -[gitflow configureMenuItemsForEntity:forMenu:withStart:andFinish:] at /Users/xx/Library/Application Support/Alcatraz/Plug-ins/gitflow/gitflow/gitflow.m:91 (in gitflow)
  8   -[gitflow reloadEntitiesToMenu:] at /Users/xx
/Library/Application Support/Alcatraz/Plug-ins/gitflow/gitflow/gitflow.m:72 (in gitflow)
  9   -[NSMenu _sendMenuOpeningNotification:](in AppKit)
 10   -[NSCarbonMenuImpl _carbonOpenEvent:handlerCallRef:](in AppKit)
 11   NSSLMMenuEventHandler (in AppKit)
 12   DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec_) (in HIToolbox)
 13   SendEventToEventTargetInternal(OpaqueEventRef_, OpaqueEventTargetRef_, HandlerCallRec_) (in HIToolbox)
 14   SendEventToEventTargetWithOptions (in HIToolbox)
 15   SendMenuOpening(MenuSelectData_, MenuData_, double, unsigned int, unsigned int, __CFDictionary_, unsigned char, unsigned char_) (in HIToolbox)
 16   _SimulateMenuOpening (in HIToolbox)
 17   -[SCTGRLIndex indexCarbonMenu:withParentMenu:resultGRLs:isRootMenu:systemHelpMenu:withDepth:](in Shortcut)
 18   -[SCTGRLIndex indexCarbonMenu:withParentMenu:resultGRLs:isRootMenu:systemHelpMenu:withDepth:](in Shortcut)
 19   -[SCTGRLIndex indexMenuBar:](in Shortcut)
 20   -[SCTSearchManager updateGRLIndex](in Shortcut)
 21   -[SCTSearchManager performSearch](in Shortcut)
 22   __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER** (in CoreFoundation)
 23   **_CFXRegistrationPost_block_invoke (in CoreFoundation)
 24   _CFXRegistrationPost (in CoreFoundation)
 25   ___CFXNotificationPost_block_invoke (in CoreFoundation)
 26   -[_CFXNotificationRegistrar find:object:observer:enumerator:](in CoreFoundation)
 27   _CFXNotificationPost (in CoreFoundation)
 28   -[NSNotificationCenter postNotificationName:object:userInfo:](in Foundation)
 29   -[NSNotificationCenter(DVTNSNotificationCenterAdditions) _dvt_postNotificationName:object:userInfo:](in DVTFoundation)
 30   __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER** (in CoreFoundation)
 31   ___CFXRegistrationPost_block_invoke (in CoreFoundation)
 32   _CFXRegistrationPost (in CoreFoundation)
 33   ___CFXNotificationPost_block_invoke (in CoreFoundation)
 34   -[_CFXNotificationRegistrar find:object:observer:enumerator:](in CoreFoundation)
 35   _CFXNotificationPost (in CoreFoundation)
 36   -[NSNotificationCenter postNotificationName:object:userInfo:](in Foundation)
 37   -[NSNotificationCenter(DVTNSNotificationCenterAdditions) _dvt_postNotificationName:object:userInfo:](in DVTFoundation)
 38   -[NSTextView(NSSharing) didChangeText](in AppKit)
 39   -[NSTextView insertText:replacementRange:](in AppKit)
 40   -[NSTextInputContext(NSInputContext_WithCompletion) insertText:replacementRange:completionHandler:](in AppKit)
 41   __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2250 (in AppKit)
 42   -[NSTextInputContext do_HandleTSMEvent_insertFixLenTextLoop:whileCondition:dispatchWorkEach:afterEachInsertText:continuation:](in AppKit)
 43   -[NSTextInputContext tryHandleTSMEvent_insertFixLenText_withContext:dispatchCondition:setupForDispatch:nestedWorkaroundCondition:nestedWorkaroundDispatchWork:loopCondition:dispatchWorkEach:afterEachInsertText:continuation:](in AppKit)
 44   __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke176 (in AppKit)
 45   __55-[NSTextInputContext handleTSMEvent:completionHandler:]_block_invoke_2 (in AppKit)
 46   -[NSTextInputContext tryHandleTSMEvent_HasMarkedText_withDispatchCondition:dispatchWork:continuation:](in AppKit)
 47   -[NSTextInputContext handleTSMEvent:completionHandler:](in AppKit)
 48   _NSTSMEventHandler (in AppKit)
 49   DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec_) (in HIToolbox)
 50   SendEventToEventTargetInternal(OpaqueEventRef_, OpaqueEventTargetRef_, HandlerCallRec_) (in HIToolbox)
 51   SendEventToEventTargetWithOptions (in HIToolbox)
 52   SendTSMEvent_WithCompletionHandler (in HIToolbox)
 53   __SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler_block_invoke (in HIToolbox)
 54   __SendFilterTextEvent_WithCompletionHandler_block_invoke (in HIToolbox)
 55   SendTSMEvent_WithCompletionHandler (in HIToolbox)
 56   SendFilterTextEvent_WithCompletionHandler (in HIToolbox)
 57   SendUnicodeTextAEToUnicodeDoc_WithCompletionHandler (in HIToolbox)
 58   __utDeliverTSMEvent_WithCompletionHandler_block_invoke_2 (in HIToolbox)
 59   __utDeliverTSMEvent_WithCompletionHandler_block_invoke (in HIToolbox)
 60   TSMKeyEvent_WithCompletionHandler (in HIToolbox)
 61   __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_4 (in HIToolbox)
 62   __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_3 (in HIToolbox)
 63   __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke_2 (in HIToolbox)
 64   __TSMProcessRawKeyEventWithOptionsAndCompletionHandler_block_invoke (in HIToolbox)
 65   TSMProcessRawKeyEventWithOptionsAndCompletionHandler (in HIToolbox)
 66   __61-[NSTextInputContext _handleEvent:options:completionHandler:]_block_invoke955 (in AppKit)
 67   -[NSTextInputContext tryTSMProcessRawKeyEvent:dispatchCondition:setupForDispatch:furtherCondition:dispatchWork:continuation:](in AppKit)
 68   -[NSTextInputContext _handleEvent:options:completionHandler:](in AppKit)
 69   -[NSTextInputContext handleEvent:](in AppKit)
 70   -[NSView interpretKeyEvents:](in AppKit)
 71   -[NSTextView keyDown:](in AppKit)
 72   -[NSWindow _reallySendEvent:isDelayedEvent:](in AppKit)
 73   -[NSWindow sendEvent:](in AppKit)
 74   -[NSCarbonWindow sendEvent:](in AppKit)
 75   -[NSCarbonMenuWindow _handleKeyEvent:](in AppKit)
 76   NSMenuItemCarbonEventHandler (in AppKit)
 77   DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec_) (in HIToolbox)
 78   SendEventToEventTargetInternal(OpaqueEventRef_, OpaqueEventTargetRef_, HandlerCallRec_) (in HIToolbox)
 79   SendEventToEventTargetWithOptions (in HIToolbox)
 80   ToolboxEventDispatcherHandler(OpaqueEventHandlerCallRef_, OpaqueEventRef_, void_) (in HIToolbox)
 81   DispatchEventToHandlers(EventTargetRec_, OpaqueEventRef_, HandlerCallRec_) (in HIToolbox)
 82   SendEventToEventTargetInternal(OpaqueEventRef_, OpaqueEventTargetRef_, HandlerCallRec_) (in HIToolbox)
 83   SendEventToEventTarget (in HIToolbox)
 84   IsUserStillTracking(MenuSelectData_, unsigned char_) (in HIToolbox)
 85   TrackMenuCommon(MenuSelectData&, unsigned char_, SelectionData_, MenuResult_, MenuResult_) (in HIToolbox)
 86   MenuSelectCore(MenuData_, Point, double, unsigned int, OpaqueMenuRef*_, unsigned short_) (in HIToolbox)
 87   _HandleMenuSelection2 (in HIToolbox)
 88   _NSHandleCarbonMenuEvent (in AppKit)
 89   _DPSNextEvent (in AppKit)
 90   -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:](in AppKit)
 91   -[DVTApplication nextEventMatchingMask:untilDate:inMode:dequeue:](in DVTKit)
 92   -[NSApplication run](in AppKit)
 93   NSApplicationMain (in AppKit)
 94  0x000000010d02239b (in Xcode)
 95   start (in libdyld.dylib)

abort() called

**Comment by aperechnev** [comment]
Yes, this is a side effect of another well known issue. I'll fix it as soon as possible. Maybe today.

**Comment by aperechnev** [comment]
Relates to #9

**Comment by aperechnev** [comment]
Fixed in new release 1.0.2. Please reinstall plugin.
